version: "3.9"
services:
  nodejs:
    container_name: nodeapp
    build: ./app
    image: jaredsparta/jenkins-task-app
    ports: 
      - "80:3000"
    environment:
      - DB_HOST=database:27017
    depends_on:
      - database

  database:
    container_name: mongodb
    image: mongo
    ports: 
      - "27017:27017"
